# Generated by Django 5.0.4 on 2024-04-19 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goallist', '0004_alter_goals_created_at_alter_goals_upload_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 10, 25, 2, 566354)),
        ),
        migrations.AlterField(
            model_name='goals',
            name='goal_condition',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='goals',
            name='upload_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 10, 25, 2, 567323)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 10, 25, 2, 566354)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='upload_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 10, 25, 2, 567323)),
        ),
        migrations.AlterModelTable(
            name='goals',
            table='Goals',
        ),
    ]
