# Generated by Django 5.0.2 on 2024-04-19 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goallist', '0008_alter_goals_created_at_alter_goals_upload_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 17, 15, 43, 89657)),
        ),
        migrations.AlterField(
            model_name='goals',
            name='upload_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 17, 15, 43, 89657)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 17, 15, 43, 89657)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='upload_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 17, 15, 43, 89657)),
        ),
    ]
