# Generated by Django 5.0.4 on 2024-04-08 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30)),
                ('address', models.EmailField(max_length=254, unique=True)),
                ('job', models.CharField(blank=True, max_length=100)),
                ('introduction', models.CharField(blank=True, max_length=500)),
                ('birthday', models.DateField(default='1900-01-01')),
                ('picture', models.FileField(upload_to='picture/')),
                ('created_at', models.DateField(default=datetime.datetime(2024, 4, 8, 2, 6, 50, 28211, tzinfo=datetime.timezone.utc))),
                ('upload_at', models.DateField(default=datetime.datetime(2024, 4, 8, 2, 6, 50, 28211, tzinfo=datetime.timezone.utc))),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
