# Generated by Django 5.0.4 on 2024-04-08 03:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.FileField(null=True, upload_to='picture/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='upload_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
