# Generated by Django 5.0.4 on 2024-04-15 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_users_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='birthday_dayofyear_internal',
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 18, 17, 6, 28333)),
        ),
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.FileField(null=True, upload_to='picture/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='upload_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 18, 17, 6, 28333)),
        ),
    ]
