# Generated by Django 5.0.4 on 2024-04-15 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_users_birthday_dayofyear_internal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 18, 18, 29, 124457)),
        ),
        migrations.AlterField(
            model_name='users',
            name='upload_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 18, 18, 29, 124457)),
        ),
    ]
