# Generated by Django 5.0.4 on 2024-04-15 09:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_users_created_at_alter_users_upload_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='users',
            name='upload_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
