# Generated by Django 5.0.4 on 2024-04-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_users_created_at_alter_users_upload_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='upload_at',
            field=models.DateTimeField(),
        ),
    ]
